name: CI Style Dictionary
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Transform Figma Tokens JSON to something Style Dictionary can read
      - run: npx token-transformer tokens.json tokens/input.json
      - run: npx token-transformer tokens.json tokens/mw.json core,default,musikwoche,components/button core
      - run: npx token-transformer tokens.json tokens/bf.json core,default,blickpunktfilm,components/button core
     # Convert tokens according to Style Dictionary config
      - run: npm install style-dictionary
      - run: npm run build
     # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
